sudo: required
servcies:
  - docker

before_install:
  - docker build -t manjunj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true manjunj/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-756895358668"
  bucker_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
